services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spy_cat_agency
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d spy_cat_agency" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sca_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      postgres:
        condition: service_healthy